/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct App {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "human_version", skip_serializing_if = "Option::is_none")]
    pub human_version: Option<String>,
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "app_metadata", skip_serializing_if = "Option::is_none")]
    pub app_metadata: Option<serde_json::Value>,
}

impl App {
    pub fn new() -> App {
        App {
            id: None,
            name: None,
            state: None,
            version: None,
            human_version: None,
            namespace: None,
            status: None,
            app_metadata: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "RUNNING")]
    Running,
    #[serde(rename = "STOPPED")]
    Stopped,
    #[serde(rename = "DEPLOYING")]
    Deploying,
    #[serde(rename = "STOPPING")]
    Stopping,
    #[serde(rename = "ERROR")]
    Error,
}

impl Default for State {
    fn default() -> State {
        Self::Running
    }
}

