/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateVmRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "vcpus")]
    pub vcpus: i32,
    #[serde(rename = "memory")]
    pub memory: i32,
    #[serde(rename = "cpu_model", skip_serializing_if = "Option::is_none")]
    pub cpu_model: Option<String>,
    #[serde(rename = "autostart", skip_serializing_if = "Option::is_none")]
    pub autostart: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "bootloader", skip_serializing_if = "Option::is_none")]
    pub bootloader: Option<String>,
    #[serde(rename = "devices", skip_serializing_if = "Option::is_none")]
    pub devices: Option<Vec<serde_json::Value>>,
}

impl CreateVmRequest {
    pub fn new(name: String, vcpus: i32, memory: i32) -> CreateVmRequest {
        CreateVmRequest {
            name,
            vcpus,
            memory,
            cpu_model: None,
            autostart: None,
            description: None,
            bootloader: None,
            devices: None,
        }
    }
}

