/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Disk {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "devname", skip_serializing_if = "Option::is_none")]
    pub devname: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "vendor", skip_serializing_if = "Option::is_none")]
    pub vendor: Option<String>,
    #[serde(rename = "smart_status", skip_serializing_if = "Option::is_none")]
    pub smart_status: Option<String>,
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<i32>,
    #[serde(rename = "hddstandby", skip_serializing_if = "Option::is_none")]
    pub hddstandby: Option<String>,
    #[serde(rename = "advpowermgmt", skip_serializing_if = "Option::is_none")]
    pub advpowermgmt: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl Disk {
    pub fn new() -> Disk {
        Disk {
            id: None,
            devname: None,
            size: None,
            model: None,
            serial: None,
            r#type: None,
            vendor: None,
            smart_status: None,
            temperature: None,
            hddstandby: None,
            advpowermgmt: None,
            status: None,
        }
    }
}

