/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DockerImagePullRequest {
    #[serde(rename = "from_image", skip_serializing_if = "Option::is_none")]
    pub from_image: Option<String>,
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

impl DockerImagePullRequest {
    pub fn new() -> DockerImagePullRequest {
        DockerImagePullRequest {
            from_image: None,
            tag: None,
        }
    }
}

