/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Group {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "gid", skip_serializing_if = "Option::is_none")]
    pub gid: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "groupwise", skip_serializing_if = "Option::is_none")]
    pub groupwise: Option<bool>,
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<Vec<String>>,
}

impl Group {
    pub fn new() -> Group {
        Group {
            id: None,
            gid: None,
            name: None,
            groupwise: None,
            users: None,
        }
    }
}

