/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KubernetesCluster {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "pods", skip_serializing_if = "Option::is_none")]
    pub pods: Option<i32>,
    #[serde(rename = "storage", skip_serializing_if = "Option::is_none")]
    pub storage: Option<serde_json::Value>,
}

impl KubernetesCluster {
    pub fn new() -> KubernetesCluster {
        KubernetesCluster {
            id: None,
            status: None,
            version: None,
            pods: None,
            storage: None,
        }
    }
}

