/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NfsExport {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "networks", skip_serializing_if = "Option::is_none")]
    pub networks: Option<Vec<String>>,
    #[serde(rename = "ro", skip_serializing_if = "Option::is_none")]
    pub ro: Option<bool>,
    #[serde(rename = "sync", skip_serializing_if = "Option::is_none")]
    pub sync: Option<bool>,
    #[serde(rename = "subtree_check", skip_serializing_if = "Option::is_none")]
    pub subtree_check: Option<bool>,
}

impl NfsExport {
    pub fn new() -> NfsExport {
        NfsExport {
            id: None,
            path: None,
            comment: None,
            networks: None,
            ro: None,
            sync: None,
            subtree_check: None,
        }
    }
}

