/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PoolQueryOptions {
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
    #[serde(rename = "order_by", skip_serializing_if = "Option::is_none")]
    pub order_by: Option<Vec<String>>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<bool>,
}

impl PoolQueryOptions {
    pub fn new() -> PoolQueryOptions {
        PoolQueryOptions {
            limit: None,
            offset: None,
            order_by: None,
            count: None,
        }
    }
}

