/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pool {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "guid", skip_serializing_if = "Option::is_none")]
    pub guid: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
    #[serde(rename = "free", skip_serializing_if = "Option::is_none")]
    pub free: Option<i32>,
    #[serde(rename = "allocated", skip_serializing_if = "Option::is_none")]
    pub allocated: Option<i32>,
    #[serde(rename = "autotrim", skip_serializing_if = "Option::is_none")]
    pub autotrim: Option<String>,
    #[serde(rename = "healthy", skip_serializing_if = "Option::is_none")]
    pub healthy: Option<bool>,
    #[serde(rename = "warning", skip_serializing_if = "Option::is_none")]
    pub warning: Option<bool>,
}

impl Pool {
    pub fn new() -> Pool {
        Pool {
            id: None,
            guid: None,
            name: None,
            status: None,
            size: None,
            free: None,
            allocated: None,
            autotrim: None,
            healthy: None,
            warning: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ONLINE")]
    Online,
    #[serde(rename = "OFFLINE")]
    Offline,
    #[serde(rename = "DEGRADED")]
    Degraded,
    #[serde(rename = "FAULTED")]
    Faulted,
}

impl Default for Status {
    fn default() -> Status {
        Self::Online
    }
}

