/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SmbShare {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "cifs_name", skip_serializing_if = "Option::is_none")]
    pub cifs_name: Option<String>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "guestok", skip_serializing_if = "Option::is_none")]
    pub guestok: Option<bool>,
    #[serde(rename = "readonly", skip_serializing_if = "Option::is_none")]
    pub readonly: Option<bool>,
    #[serde(rename = "browsable", skip_serializing_if = "Option::is_none")]
    pub browsable: Option<bool>,
    #[serde(rename = "export", skip_serializing_if = "Option::is_none")]
    pub export: Option<String>,
}

impl SmbShare {
    pub fn new() -> SmbShare {
        SmbShare {
            id: None,
            cifs_name: None,
            path: None,
            comment: None,
            guestok: None,
            readonly: None,
            browsable: None,
            export: None,
        }
    }
}

