/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemInfo {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(rename = "hostname", skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(rename = "cpu_model", skip_serializing_if = "Option::is_none")]
    pub cpu_model: Option<String>,
    #[serde(rename = "cpu_cores", skip_serializing_if = "Option::is_none")]
    pub cpu_cores: Option<i32>,
    #[serde(rename = "cpu_threads", skip_serializing_if = "Option::is_none")]
    pub cpu_threads: Option<i32>,
    #[serde(rename = "memory_total", skip_serializing_if = "Option::is_none")]
    pub memory_total: Option<i32>,
    #[serde(rename = "memory_free", skip_serializing_if = "Option::is_none")]
    pub memory_free: Option<i32>,
    #[serde(rename = "uptime_seconds", skip_serializing_if = "Option::is_none")]
    pub uptime_seconds: Option<i32>,
    #[serde(rename = "loadavg", skip_serializing_if = "Option::is_none")]
    pub loadavg: Option<Vec<f64>>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<String>,
    #[serde(rename = "build_time", skip_serializing_if = "Option::is_none")]
    pub build_time: Option<String>,
}

impl SystemInfo {
    pub fn new() -> SystemInfo {
        SystemInfo {
            version: None,
            hostname: None,
            cpu_model: None,
            cpu_cores: None,
            cpu_threads: None,
            memory_total: None,
            memory_free: None,
            uptime_seconds: None,
            loadavg: None,
            model: None,
            serial: None,
            build_time: None,
        }
    }
}

