/*
 * TrueNAS REST API
 *
 * TrueNAS Scale/CORE REST API v2.0
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "uid", skip_serializing_if = "Option::is_none")]
    pub uid: Option<i32>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "full_name", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<i32>,
    #[serde(rename = "groups", skip_serializing_if = "Option::is_none")]
    pub groups: Option<Vec<i32>>,
    #[serde(rename = "home", skip_serializing_if = "Option::is_none")]
    pub home: Option<String>,
    #[serde(rename = "shell", skip_serializing_if = "Option::is_none")]
    pub shell: Option<String>,
    #[serde(rename = "password_disabled", skip_serializing_if = "Option::is_none")]
    pub password_disabled: Option<bool>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "sudo", skip_serializing_if = "Option::is_none")]
    pub sudo: Option<bool>,
}

impl User {
    pub fn new() -> User {
        User {
            id: None,
            uid: None,
            username: None,
            full_name: None,
            email: None,
            password: None,
            group: None,
            groups: None,
            home: None,
            shell: None,
            password_disabled: None,
            locked: None,
            sudo: None,
        }
    }
}

